spring.application.name=crm-system

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/crm_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================
jwt.secretKey=QmFzZTY0U2VjcmV0S2V5X1ZpZUVtcDNfMjAyNl9TdHJvbmc=
jwt.accessToken.expiration=3600000
jwt.refreshToken.expiration=604800000

# ===============================
# ADMIN CONFIG
# ===============================
admin.username=admincrm
admin.email=admincrm@gmail.com
admin.password=123456

api.crm-system-url=/crm-system/api
